### PR TITLE
added Sliding window algo in java

### PR DESCRIPTION
**Pull request by AntrikshBatra**
Question no. 239 on leetcode ----  https://leetcode.com/problems/sliding-window-maximum/

### CODE REVIEW

**Comment by AntrikshBatra** [comment]
Please review my pr, in case of any conflict let me know I will fix it.
I would be thankful if u add the label as hacktoberfest-accepted.

**Review by prathamesh-borse — CHANGES_REQUESTED** [review]
Hey, @AntrikshBatra it would be great if you add the link of this Question.

**Comment by AntrikshBatra** [comment]
Question Link ---https://leetcode.com/problems/sliding-window-maximum/

**Comment by AntrikshBatra** [comment]
@prathamesh-borse
Done with the required changes...

**Review by prathamesh-borse — APPROVED** [review]
Your PR looks good.
@AntrikshBatra Thanks for making your contribution to the open-source world and stepping your feet in the open-source community.
Happy Hacking.! 👍 💯

**Pull request merged**
